[tool.poetry]
name = "pandocsql"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.5"
panflute = "^1.11"

[tool.poetry.dev-dependencies]
ipython = "^7.9"

[tool.poetry.scripts]
pandocsql = 'pandocsql:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
